#!/bin/sh
# Script to be executed after a successfull commit.
# $Date: 2012-10-28 17:16:00 +0100 $
# 
# Looks for files changed in the last commit, removes those files and checks
# them out again to refresh the keywords. Keyword expansion only works should
# in files that have the kw filter set in .gitattibutes.

FILES=`ls *.py *.1 *.5`
rm -f $FILES
git checkout -f $FILES

